// <auto-generated />
namespace TaskManagerDAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Fix_Task : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Fix_Task));
        
        string IMigrationMetadata.Id
        {
            get { return "201805072025458_Fix _Task"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
